name: RewardCodes
version: 1.2.0
main: com.electro2560.dev.RewardCodes.RewardCodes
website: http://dev.electro2560.com/
description: Create rewards for items and permissions that can be received by players by entering a code.
commands:
  redeem:
    aliases: [rcodes, rcode]
    description: Redeem a reward using a code