name: RewardCodes
version: ${project.version}
api-version: 1.13
main: com.electro2560.dev.rewardcodes.RewardCodes
website: https://dev.electro2560.com/
description: Create rewards for items and permissions that can be received by players by entering a code.
commands:
  redeem:
    aliases: [rcodes, rcode]
    description: Redeem a reward using a code